spring:
  datasource:
    url: jdbc:postgresql://localhost/traderepublic?useSSL=false
    username: traderepublic_user
    password: 1234
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
